FROM node:20-alpine AS build

WORKDIR /app

COPY frontend_keycloak/package.json ./
RUN npm install

COPY frontend_keycloak/ .

ENV REACT_APP_KEYCLOAK_URL=http://group02.local/auth/
ENV REACT_APP_KEYCLOAK_REALM=frcm-realm
ENV REACT_APP_KEYCLOAK_CLIENT_ID=frcm-react-app-client
ENV REACT_APP_API=http://group02.local/api/v1

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]