FROM python:3.12-slim-bookworm

ENV PYTHONPATH=/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY --from=docker.io/astral/uv:0.9.28 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml ./

RUN uv sync --no-install-project

COPY src/ ./src/


CMD ["uv", "run", "python", "src/mqtt/frcm_publisher.py", "--configfile=src/mqtt/connector/config-ada502-pub.yml"]