FROM node:20-alpine AS build

WORKDIR /app

COPY frontend_keycloak/package.json ./
RUN npm install

COPY frontend_keycloak/ .

ARG REACT_APP_API=https://fireriskgroup02.com/api/v1
ARG REACT_APP_KEYCLOAK_URL=https://fireriskgroup02.com/auth
ARG REACT_APP_KEYCLOAK_REALM=frcm-realm
ARG REACT_APP_KEYCLOAK_CLIENT_ID=frcm-react-app-client

ENV REACT_APP_API=$REACT_APP_API
ENV REACT_APP_KEYCLOAK_URL=$REACT_APP_KEYCLOAK_URL
ENV REACT_APP_KEYCLOAK_REALM=$REACT_APP_KEYCLOAK_REALM
ENV REACT_APP_KEYCLOAK_CLIENT_ID=$REACT_APP_KEYCLOAK_CLIENT_ID

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]