FROM python:3.12-slim-bookworm

ENV PYTHONPATH=/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install uv binary
COPY --from=docker.io/astral/uv:0.9.28 /uv /uvx /bin/

WORKDIR /app


# copy dependency files first (layer caching)
COPY pyproject.toml README.md ./
RUN uv sync --no-install-project


COPY src/ ./src/

CMD ["uv", "run", "firerisk-api"]
