apiVersion: v1
data:
  APP_HOST: 0.0.0.0
  APP_PORT: "6767"
  CLIENT_ID: frcm-api-client
  KEYCLOAK_INTERNAL_URL: http://keycloak.group02.svc.cluster.local:8888/auth/
  KEYCLOAK_PUBLIC_URL: http://group02.local/auth/
  REALM: frcm-realm
  TIMESCALE_DATABASE: timescaledb
  TIMESCALE_HOST: timescaledb.group02.svc.cluster.local
  TIMESCALE_PORT: "5432"
  TIMESCALE_SCHEMA: public
  TIMESCALE_USER: timescale
kind: ConfigMap
metadata:
  name: frcm-api-config
  namespace: group02
