server {
  listen 443 ssl;
  server_name fireriskgroup02.com www.fireriskgroup02.com;

  ssl_certificate     /etc/letsencrypt/live/auth.fireriskgroup02.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/auth.fireriskgroup02.com/privkey.pem;

  location / {
    return 200 "Frontend not deployed yet.\n";
    add_header Content-Type text/plain;
  }
}