apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firerisk-ingress
  namespace: group02
spec:
  ingressClassName: nginx
  rules:
    - host: group02.local
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8888
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: frcm-api
                port:
                  number: 6767
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
                  
                  